package cmd

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	cobradoc "github.com/spf13/cobra/doc"
)

const (
	DefaultReferenceDocsDir = "docs/reference/cli"
	DefaultManpagesDir      = "share/man/man1"
	DefaultCompletionsDir   = "share/completions"
)

type DocsOptions struct {
	ReferenceDir  string
	ManDir        string
	CompletionDir string
}

func GenerateDocs(options DocsOptions) error {
	root := NewRoot(Options{})
	disableAutoGenTags(root)

	referenceDir := firstNonEmpty(options.ReferenceDir, DefaultReferenceDocsDir)
	manDir := firstNonEmpty(options.ManDir, DefaultManpagesDir)
	completionDir := firstNonEmpty(options.CompletionDir, DefaultCompletionsDir)

	if err := prepareGeneratedDir(referenceDir, "beehiiv*.md"); err != nil {
		return err
	}
	if err := prepareGeneratedDir(manDir, "beehiiv*.1"); err != nil {
		return err
	}
	if err := prepareGeneratedDir(completionDir, "*"); err != nil {
		return err
	}

	if err := cobradoc.GenMarkdownTreeCustom(root, referenceDir, markdownPrepender, func(link string) string {
		return link
	}); err != nil {
		return fmt.Errorf("generate markdown docs: %w", err)
	}
	if err := normalizeGeneratedMarkdown(referenceDir); err != nil {
		return fmt.Errorf("normalize markdown docs: %w", err)
	}

	if err := cobradoc.GenManTree(root, &cobradoc.GenManHeader{
		Manual: "Beehiiv CLI Manual",
		Source: "beehiiv-cli",
	}, manDir); err != nil {
		return fmt.Errorf("generate manpages: %w", err)
	}
	if err := generateCompletions(root, completionDir); err != nil {
		return fmt.Errorf("generate shell completions: %w", err)
	}

	return nil
}

func prepareGeneratedDir(dir string, pattern string) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	matches, err := filepath.Glob(filepath.Join(dir, pattern))
	if err != nil {
		return err
	}
	for _, match := range matches {
		if err := os.Remove(match); err != nil && !os.IsNotExist(err) {
			return err
		}
	}

	return nil
}

func markdownPrepender(string) string {
	return "<!-- Code generated by `go run ./cmd/gen-docs`; DO NOT EDIT. -->\n\n"
}

func normalizeGeneratedMarkdown(referenceDir string) error {
	matches, err := filepath.Glob(filepath.Join(referenceDir, "beehiiv*.md"))
	if err != nil {
		return err
	}

	for _, match := range matches {
		data, err := os.ReadFile(match)
		if err != nil {
			return err
		}
		normalized := strings.TrimRight(string(data), "\n") + "\n"
		if normalized == string(data) {
			continue
		}
		if err := os.WriteFile(match, []byte(normalized), 0o644); err != nil {
			return err
		}
	}

	return nil
}

func generateCompletions(root *cobra.Command, completionDir string) error {
	type completionTarget struct {
		name     string
		filename string
		render   func(*bytes.Buffer) error
	}

	targets := []completionTarget{
		{
			name:     "bash",
			filename: "beehiiv.bash",
			render: func(buffer *bytes.Buffer) error {
				return root.GenBashCompletionV2(buffer, true)
			},
		},
		{
			name:     "fish",
			filename: "beehiiv.fish",
			render: func(buffer *bytes.Buffer) error {
				return root.GenFishCompletion(buffer, true)
			},
		},
		{
			name:     "powershell",
			filename: "beehiiv.ps1",
			render: func(buffer *bytes.Buffer) error {
				return root.GenPowerShellCompletionWithDesc(buffer)
			},
		},
		{
			name:     "zsh",
			filename: "_beehiiv",
			render: func(buffer *bytes.Buffer) error {
				return root.GenZshCompletion(buffer)
			},
		},
	}

	for _, target := range targets {
		var buffer bytes.Buffer
		if err := target.render(&buffer); err != nil {
			return fmt.Errorf("%s completion: %w", target.name, err)
		}
		if err := os.WriteFile(filepath.Join(completionDir, target.filename), buffer.Bytes(), 0o644); err != nil {
			return err
		}
	}

	return nil
}

func disableAutoGenTags(command *cobra.Command) {
	command.DisableAutoGenTag = true
	for _, child := range command.Commands() {
		disableAutoGenTags(child)
	}
}
