package cmd

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateDocsCreatesReferenceDocsAndManpages(t *testing.T) {
	t.Parallel()

	tempDir := t.TempDir()
	referenceDir := filepath.Join(tempDir, "reference")
	manDir := filepath.Join(tempDir, "man1")
	completionDir := filepath.Join(tempDir, "completions")

	if err := os.MkdirAll(referenceDir, 0o755); err != nil {
		t.Fatalf("MkdirAll(referenceDir): %v", err)
	}
	if err := os.MkdirAll(manDir, 0o755); err != nil {
		t.Fatalf("MkdirAll(manDir): %v", err)
	}
	if err := os.MkdirAll(completionDir, 0o755); err != nil {
		t.Fatalf("MkdirAll(completionDir): %v", err)
	}
	if err := os.WriteFile(filepath.Join(referenceDir, "beehiiv_stale.md"), []byte("stale"), 0o644); err != nil {
		t.Fatalf("WriteFile(stale markdown): %v", err)
	}
	if err := os.WriteFile(filepath.Join(manDir, "beehiiv-stale.1"), []byte("stale"), 0o644); err != nil {
		t.Fatalf("WriteFile(stale manpage): %v", err)
	}
	if err := os.WriteFile(filepath.Join(completionDir, "stale.txt"), []byte("stale"), 0o644); err != nil {
		t.Fatalf("WriteFile(stale completion): %v", err)
	}

	err := GenerateDocs(DocsOptions{
		ReferenceDir:  referenceDir,
		ManDir:        manDir,
		CompletionDir: completionDir,
	})
	if err != nil {
		t.Fatalf("GenerateDocs returned error: %v", err)
	}

	if _, err := os.Stat(filepath.Join(referenceDir, "beehiiv_stale.md")); !os.IsNotExist(err) {
		t.Fatalf("stale markdown file was not removed: %v", err)
	}
	if _, err := os.Stat(filepath.Join(manDir, "beehiiv-stale.1")); !os.IsNotExist(err) {
		t.Fatalf("stale manpage file was not removed: %v", err)
	}
	if _, err := os.Stat(filepath.Join(completionDir, "stale.txt")); !os.IsNotExist(err) {
		t.Fatalf("stale completion file was not removed: %v", err)
	}

	rootDoc, err := os.ReadFile(filepath.Join(referenceDir, "beehiiv.md"))
	if err != nil {
		t.Fatalf("ReadFile(root markdown): %v", err)
	}
	rootText := string(rootDoc)
	if !strings.Contains(rootText, "## beehiiv") {
		t.Fatalf("root markdown missing command heading: %s", rootText)
	}
	if !strings.Contains(rootText, "--output") {
		t.Fatalf("root markdown missing global flags: %s", rootText)
	}
	if !strings.Contains(rootText, "beehiiv_completion.md") {
		t.Fatalf("root markdown missing completion command link: %s", rootText)
	}
	if strings.Contains(rootText, "Auto generated by spf13/cobra") {
		t.Fatalf("root markdown should not include Cobra auto-generation footer: %s", rootText)
	}

	listDoc, err := os.ReadFile(filepath.Join(referenceDir, "beehiiv_publications_list.md"))
	if err != nil {
		t.Fatalf("ReadFile(list markdown): %v", err)
	}
	listText := string(listDoc)
	if !strings.Contains(listText, "--query") {
		t.Fatalf("list markdown missing query flag: %s", listText)
	}
	if !strings.Contains(listText, "--all") {
		t.Fatalf("list markdown missing pagination flag: %s", listText)
	}

	rootMan, err := os.ReadFile(filepath.Join(manDir, "beehiiv.1"))
	if err != nil {
		t.Fatalf("ReadFile(root manpage): %v", err)
	}
	manText := string(rootMan)
	if !strings.Contains(manText, "Beehiiv CLI Manual") {
		t.Fatalf("root manpage missing manual header: %s", manText)
	}
	if !strings.Contains(manText, "--output") {
		t.Fatalf("root manpage missing global flag section: %s", manText)
	}

	for _, name := range []string{"beehiiv.bash", "beehiiv.fish", "beehiiv.ps1", "_beehiiv"} {
		data, err := os.ReadFile(filepath.Join(completionDir, name))
		if err != nil {
			t.Fatalf("ReadFile(%s): %v", name, err)
		}
		if !strings.Contains(string(data), "beehiiv") {
			t.Fatalf("%s missing command name: %s", name, string(data))
		}
	}
}
