.nh
.TH "BEEHIIV-CUSTOM-FIELDS-REPLACE" "1" "Apr 2026" "beehiiv-cli" "Beehiiv CLI Manual"

.SH NAME
beehiiv-custom-fields-replace - Update custom field


.SH SYNOPSIS
\fBbeehiiv custom-fields replace  [flags]\fP


.SH DESCRIPTION
Update custom field

.PP
Update a custom field on a publication

.PP
API path: /publications/{publicationId}/custom_fields/{id}


.SH OPTIONS
\fB--body\fP=""
	Provide a request body as inline JSON, @path, or - for stdin

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for replace

.PP
\fB--query\fP=[]
	Add a repeatable query parameter in key=value form


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	Override the Beehiiv API key

.PP
\fB--base-url\fP=""
	Override the API base URL

.PP
\fB--compact\fP[=false]
	Print compact JSON

.PP
\fB--config\fP=""
	Override the settings file location

.PP
\fB--debug\fP[=false]
	Print request URLs to stderr

.PP
\fB--output\fP=""
	Choose the output format (json, table, raw)

.PP
\fB--publication-id\fP=""
	Override the Beehiiv publication ID

.PP
\fB--rate-limit-rpm\fP=0
	Override the internal rate limit

.PP
\fB--raw\fP[=false]
	Shorthand for --output raw

.PP
\fB--table\fP[=false]
	Shorthand for --output table

.PP
\fB--timeout\fP=""
	Override the request timeout, e.g. 45s

.PP
\fB--verbose\fP[=false]
	Print request and response details to stderr


.SH SEE ALSO
\fBbeehiiv-custom-fields(1)\fP
