.nh
.TH "BEEHIIV-SEGMENTS" "1" "Apr 2026" "beehiiv-cli" "Beehiiv CLI Manual"

.SH NAME
beehiiv-segments - Inspect and manage publication segments


.SH SYNOPSIS
\fBbeehiiv segments [flags]\fP


.SH DESCRIPTION
List segments, inspect a single segment, recalculate it, and jump into segment members or lightweight results.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for segments


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--api-key\fP=""
	Override the Beehiiv API key

.PP
\fB--base-url\fP=""
	Override the API base URL

.PP
\fB--compact\fP[=false]
	Print compact JSON

.PP
\fB--config\fP=""
	Override the settings file location

.PP
\fB--debug\fP[=false]
	Print request URLs to stderr

.PP
\fB--output\fP=""
	Choose the output format (json, table, raw)

.PP
\fB--publication-id\fP=""
	Override the Beehiiv publication ID

.PP
\fB--rate-limit-rpm\fP=0
	Override the internal rate limit

.PP
\fB--raw\fP[=false]
	Shorthand for --output raw

.PP
\fB--table\fP[=false]
	Shorthand for --output table

.PP
\fB--timeout\fP=""
	Override the request timeout, e.g. 45s

.PP
\fB--verbose\fP[=false]
	Print request and response details to stderr


.SH EXAMPLE
.EX
beehiiv segments list
beehiiv segments show segment_123
beehiiv segments members segment_123 --query expand=stats,custom_fields
beehiiv segments results segment_123
.EE


.SH SEE ALSO
\fBbeehiiv(1)\fP, \fBbeehiiv-segments-delete(1)\fP, \fBbeehiiv-segments-get(1)\fP, \fBbeehiiv-segments-list(1)\fP, \fBbeehiiv-segments-members(1)\fP, \fBbeehiiv-segments-recalculate(1)\fP, \fBbeehiiv-segments-results(1)\fP
